default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: <%= ENV["COOKBOOK_DATABASE_PASSWORD"] %>

development:
  <<: *default
  database: cookbook_development

test:
  <<: *default
  database: cookbook_test

production:
  <<: *default
  database: cookbook_production