default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("COOKBOOK_DATABASE_USERNAME") { "postgres" } %>
  password: <%= ENV.fetch("COOKBOOK_DATABASE_PASSWORD") { "postgres" } %>
  host: localhost

development:
  <<: *default
  database: cookbook_development

test:
  <<: *default
  database: cookbook_test

production:
  <<: *default
  database: cookbook_production
